name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: qbittorrent_pia-wireguard_port-forward_qbittorrent-port-helper
    - uses: actions/checkout@v2
      run: docker build . --file Dockerfile --tag qbittorrent_pia-wireguard_port-forward_qbittorrent-port-helper
