name: qbittorrent_pia-wireguard_port-forward_qbittorrent-port-helper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: qbittorrent_pia-wireguard_port-forward_qbittorrent-port-helper
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
